library(quantmod)
library(quadprog)
library(moments)
library(urca)
library(DEoptim)
library(Rsolnp)
library(quantmod)
library(extraDistr)
library(LaplacesDemon)

source("GAS_proces.r")
source("Matrix_power.r")
source("Unconditional_param2.r")
source("Normal_distr.r")
source("Student_t.r")
source("AST.r")
source("SST.r")
source("Laplace_A.r")
source("Laplace.r")

load("data.RData")

