library(quantmod)
library(quadprog)
library(moments)
library(urca)
library(DEoptim)
library(Rsolnp)
library(quantmod)
library(extraDistr)
library(LaplacesDemon)
library(GAS)
library(MCS)

source("GAS_proces.r")
source("Matrix_power.r")
source("Unconditional_param.r")
source("Normal.r")
source("Student.r")
source("AST.r")
source("SST.r")
source("Laplace_A.r")
source("Laplace.r")
source("q_ST.r")
source("test_VaR.r")

load("data.RData")

